/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasireservasi;

/**
 *
 * @author USER
 */
public class LogOut extends javax.swing.JFrame {

    /**
     * Creates new form LogOut
     */
    public LogOut() {
        initComponents();
        jLabel4.setText(Register.fullname + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_Home = new javax.swing.JButton();
        jButton_JadwalPemotretan = new javax.swing.JButton();
        jButton_ReservasiPemotretan = new javax.swing.JButton();
        jButton_LogOut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_iyaLogout = new javax.swing.JButton();
        jButton_Batal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(30, 144, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("name");

        jButton_Home.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Home.setText("Home");
        jButton_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HomeActionPerformed(evt);
            }
        });

        jButton_JadwalPemotretan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_JadwalPemotretan.setText("Jadwal Pemotretan");
        jButton_JadwalPemotretan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_JadwalPemotretanActionPerformed(evt);
            }
        });

        jButton_ReservasiPemotretan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_ReservasiPemotretan.setText("Reservasi Pemotretan");
        jButton_ReservasiPemotretan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ReservasiPemotretanActionPerformed(evt);
            }
        });

        jButton_LogOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_LogOut.setText("Log out");
        jButton_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_JadwalPemotretan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addComponent(jButton_ReservasiPemotretan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)))
                .addGap(37, 37, 37)
                .addComponent(jButton_Home)
                .addGap(18, 18, 18)
                .addComponent(jButton_JadwalPemotretan)
                .addGap(18, 18, 18)
                .addComponent(jButton_ReservasiPemotretan)
                .addGap(18, 18, 18)
                .addComponent(jButton_LogOut)
                .addContainerGap(433, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 310, 700);

        jPanel2.setBackground(new java.awt.Color(43, 191, 254));
        jPanel2.setMinimumSize(new java.awt.Dimension(697, 350));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("@ Hak Cipta 2023 | Photography Studio | Jl. Sungai Larona No.09, Ussu, Kec. Wara Utara, Kota Palopo.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Peringatan!!!");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Apakah Anda yakin ingin keluar dari aplikasi ini?");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Anda harus login kembali jika ingin masuk ke Aplikasi Reservasi Studio Foto");

        jButton_iyaLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_iyaLogout.setText("Iya");
        jButton_iyaLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iyaLogoutActionPerformed(evt);
            }
        });

        jButton_Batal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Batal.setText("Tidak");
        jButton_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 165, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(212, 212, 212))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(503, 503, 503)
                .addComponent(jButton_iyaLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Batal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_iyaLogout)
                    .addComponent(jButton_Batal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 497, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(310, 0, 1060, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_JadwalPemotretanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_JadwalPemotretanActionPerformed
        // TODO add your handling code here:

        JadwalPemotretan jadwalFrame = new JadwalPemotretan(); // Membuat instance dari JFrame "Jadwal Pemotretan"
        jadwalFrame.setVisible(true); // Menampilkan JFrame "Jadwal Pemotretan"
        // this.dispose(); // Hapus baris ini untuk menjaga frame Home tetap terbuka
    }//GEN-LAST:event_jButton_JadwalPemotretanActionPerformed

    private void jButton_ReservasiPemotretanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ReservasiPemotretanActionPerformed
        // TODO add your handling code here:
        ReservasiPemotretan reservasipemotretanFrame = new ReservasiPemotretan(); // Membuat instance dari JFrame "Jadwal Pemotretan"
        reservasipemotretanFrame.setVisible(true); // Menampilkan JFrame "Jadwal Pemotretan"
        // this.dispose(); // Hapus baris ini untuk menjaga frame Home tetap terbuka
    }//GEN-LAST:event_jButton_ReservasiPemotretanActionPerformed

    private void jButton_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HomeActionPerformed
        // TODO add your handling code here:
        Home homeFrame = new Home(); 
        homeFrame.setVisible(true); 
        // this.dispose(); 
    }//GEN-LAST:event_jButton_HomeActionPerformed

    private void jButton_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogOutActionPerformed
        // TODO add your handling code here:
        LogOut logoutFrame = new LogOut(); 
        logoutFrame.setVisible(true); 
        // this.dispose(); 
    }//GEN-LAST:event_jButton_LogOutActionPerformed

    private void jButton_iyaLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iyaLogoutActionPerformed
        // TODO add your handling code here:
         Login loginFrame = new Login();  
        loginFrame.setVisible(true); 
    // this.dispose();
    }//GEN-LAST:event_jButton_iyaLogoutActionPerformed

    private void jButton_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BatalActionPerformed
        // TODO add your handling code here:
        LogOut logoutFrame = new LogOut();  
        logoutFrame.setVisible(true); 
    }//GEN-LAST:event_jButton_BatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Batal;
    private javax.swing.JButton jButton_Home;
    private javax.swing.JButton jButton_JadwalPemotretan;
    private javax.swing.JButton jButton_LogOut;
    private javax.swing.JButton jButton_ReservasiPemotretan;
    private javax.swing.JButton jButton_iyaLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
